version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-simple-chat}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "${POSTGRES_DB_PORT:-5432}:${POSTGRES_DB_PORT:-5432}"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@postgres.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeme}
    ports:
      - "${PGADMIN_DEFAULT_PORT:-15432}:80"
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:

volumes:
  postgres-data:
